import {
  BarChart3,
  Bell,
  Building2,
  ClipboardList,
  Crown,
  LayoutDashboard,
  LifeBuoy,
  MapPin,
  Settings2,
  ShieldCheck,
  Sparkles,
  TicketPercent,
  Truck,
  Users,
  Wallet,
  Landmark,
  Mail,
} from "lucide-react";

/** Central route map for the QuickPress Admin console. */
export const adminRoutes = {
  auth: "/auth",
  forgotPassword: "/forgot-password",
  dashboard: "/dashboard",
  orders: "/orders",
  customers: "/customers",
  partners: "/partners",
  riders: "/riders",
  services: "/services",
  cities: "/cities",
  financeEngine: "/finance-engine",
  wallet: "/wallet",
  coupons: "/coupons",
  memberships: "/memberships",
  notifications: "/notifications",
  emails: "/emails",
  analytics: "/analytics",
  support: "/support",
  staff: "/staff",
  settings: "/settings",
} as const;

export const adminNavItems = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard, to: adminRoutes.dashboard },
  { id: "orders", label: "Orders", icon: ClipboardList, to: adminRoutes.orders },
  { id: "customers", label: "Customers", icon: Users, to: adminRoutes.customers },
  { id: "partners", label: "Partners", icon: Building2, to: adminRoutes.partners },
  { id: "riders", label: "Riders", icon: Truck, to: adminRoutes.riders },
  { id: "services", label: "Services", icon: Sparkles, to: adminRoutes.services },
  { id: "cities", label: "Cities", icon: MapPin, to: adminRoutes.cities },
  { id: "finance-engine", label: "Finance Engine", icon: Landmark, to: adminRoutes.financeEngine },
  { id: "wallet", label: "Wallet", icon: Wallet, to: adminRoutes.wallet },
  { id: "coupons", label: "Coupons", icon: TicketPercent, to: adminRoutes.coupons },
  { id: "memberships", label: "Memberships", icon: Crown, to: adminRoutes.memberships },
  { id: "notifications", label: "Notifications", icon: Bell, to: adminRoutes.notifications },
  { id: "emails", label: "Email Hub", icon: Mail, to: adminRoutes.emails },
  { id: "analytics", label: "Analytics", icon: BarChart3, to: adminRoutes.analytics },
  { id: "support", label: "Support", icon: LifeBuoy, to: adminRoutes.support },
  { id: "staff", label: "Staff", icon: ShieldCheck, to: adminRoutes.staff },
  { id: "settings", label: "Settings", icon: Settings2, to: adminRoutes.settings },
] as const;